### ISSUE TITLE
Log driver awslogs requires options

### ISSUE THREAD

**Issue by monelgordillo** [terraform-aws-modules/terraform-aws-ecs#173]
## Description

I have set cloudwatch_log_group_name.  However, I am getting "Error: creating ECS Task Definition (ddagent-p): ClientException: Log driver awslogs requires options: awslogs-group". The example does not set awslogs-group.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 5.9.1

- Terraform version: 1.7.3

- Provider version(s): aws v5.37.0

## Reproduction Code [Required]

My terraform configuration file is pretty similar to the EC2 example:

```
      enable_cloudwatch_logging              = true
      create_cloudwatch_log_group            = true
      cloudwatch_log_group_name              = "/aws/ecs/X-p"
      cloudwatch_log_group_retention_in_days = 7
      log_configuration = {
        logDriver = "awslogs"
        options = {
          awslogs-region        = "X-X-2"
        }
      }
```

## Expected behavior

ECS service is created with related cloudwatch log group.

## Actual behavior

Error: creating ECS Task Definition (X-p): ClientException: Log driver awslogs requires options: awslogs-group

**Comment by ivan-sukhomlyn** [comment]
@monelgordillo @bryantbiggs yes, the current example is not fully correct because Terraform **doesn't support deep map merge**. My apologies that I didn't pay attention to Terraform's shallow merge behavior while making it.

I've prepared a fix for the EC2 example - https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/170

Based on that, to define a custom `log_configuration` it's required to define a **whole** config or use defaults defined at the appropriate local.
https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/45f532c06488d84f140af36241d164facb5e05f5/modules/container-definition/main.tf#L8-L18
