### ISSUE TITLE
Can we support RestartPolicy

### ISSUE THREAD

**Issue by RRosalia** [terraform-aws-modules/terraform-aws-ecs#230]
## Is your request related to a problem? Please describe.
AWS ECS now supports restart policy to restart a container without restarting the whole tasks.

## Describe the solution you'd like.
Implementation of: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy-example.html 

## Describe alternatives you've considered.
None for now i just wait until this has been added.

**Comment by bryantbiggs** [comment]
Does the Terraform provider support this?

**Comment by psantus** [comment]
Yes it does! Since July it relies on SDK v2 and the Container Definition [directly relies on SDK types](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecs/container_definitions.go#L46C1-L46C53).

I've tried it using vanilla provider and it works fine.

**Comment by psantus** [comment]
@RRosalia coming soon :)

**Comment by psantus** [comment]
@bryantbiggs I've opened a PR for this and completed all requirements (pre-commit hook and deployment)

**Comment by bryantbiggs** [comment]
this is a recent addition and while its not apparent from the provider, its only available since August 15, 2024 https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-ecs-restart-containers-task-relaunch/ (the container definition is not an actual Terraform resource currently, so its API is somewhat opaque and just accepts a json blob from the task definition or task set create API call)

Which means this requires the Terraform AWS provider of 5.63 at minimum

**Comment by bryantbiggs** [comment]
resolved in #231 and will go out in `v6.0`

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
