### ISSUE TITLE
 ECS Service Linked Role does not exist

### ISSUE THREAD

**Issue by jmstallard** [terraform-aws-modules/terraform-aws-ecs#26]
Just downloaded & ran with given example code and received this error:
module.ecs_example_complete-ecs.aws_ecs_capacity_provider.prov1: Creating...

Error: error creating capacity provider: ClientException: ECS Service Linked Role does not exist. Please create a Service linked role for ECS and try again.

**Comment by antonbabenko** [comment]
Thanks for opening this issue.

It seems that you are missing [aws_iam_service_linked_role resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_service_linked_role):

```terraform
resource "aws_iam_service_linked_role" "ecs" {
  aws_service_name = "ecs.amazonaws.com"
}
```

I am not sure whether this module should create it because it is often shared across multiple resources (AFAIK).

**Comment by jmstallard** [comment]
Thanks! Yep, works. makes sense to create this resource outside.
I'm getting this now:
Error: InvalidParameterException: There are no capacity providers with a weight value greater than zero defined in the default capacity provider strategy. At least one capacity provider must have a weight value greater than zero specified. Update the cluster's default capacity provider strategy or specify a valid capacity provider strategy and try again. "hello_world"
p.s. I'm just now deep diving into terraform, still learning. I'll look into this error.

**Comment by antonbabenko** [comment]
Sure, take a look at examples code while you are learning it.

Meanwhile, I will close this issue here :)

**Comment by richardj-bsquare** [comment]
There is still a hole in this as a solution.

If you are creating a generic module for deploying to multiple environments, then it is possible that some AWS accounts already have clusters running (let's call them brown-field accounts), and therefore they already have the service-linked role. That means the above solution will fail. You end up having to know if the service-linked role exists and optionally create the service-linked role (using count tied to a var), which when you have dozens of accounts is quite a management overhead.

aws_ecs_cluster was altered to create the service-linked role if it didn't exist; I believe the capacity provider needs to do the same since if you need to create a cluster with a capacity provider you are then in a catch-22 situation.

Our workaround in this respect is quite ugly, we create an empty unused cluster (which as a side-effect might create the service-linked role), and make the capacity provider depend on that; we then can create our real cluster with using the capacity provider; quite ugly but works for both green-field and brown-field accounts.

**Comment by antonbabenko** [comment]
Do you know how to create service-linked role **if it didn't exist in this AWS account**? Please show if you do.

**Comment by richardj-bsquare** [comment]
Creating a cluster via aws_ecs_cluster creates the service-linked role if it doesn't exist, so the mechanism is already there if that's what you mean?

**Comment by DylanBohlender** [comment]
@richardj-bsquare - thanks for posting your brown-field workaround idea. Despite its ugliness, it got the job done for us.

**Comment by irisoliver** [comment]
I'm not entirely sure if this is relevant, but we had this problem and we fixed it on "green-field" accounts by creating the service linked role (as @antonbabenko suggested) and making the capacity provider depend on it
```
resource "aws_iam_service_linked_role" "ecs" {
  aws_service_name = "ecs.amazonaws.com"
}
resource "aws_ecs_capacity_provider" "capacity_provider" {
  name = "${aws_autoscaling_group.asg.name}_provider"
  auto_scaling_group_provider {
    auto_scaling_group_arn         = aws_autoscaling_group.asg.arn
    managed_termination_protection = "ENABLED"
    managed_scaling {
      maximum_scaling_step_size = 10
      minimum_scaling_step_size = 1
      target_capacity           = 100
    }
  }
  depends_on = [
    aws_iam_service_linked_role.ecs
  ]
}
```
this might be a fluke as we had some problems before this that seemed to magically fix themselves but I hope this helps someone

**Comment by mavogel** [comment]
yes, @irisoliver this works for me as well and is a clean solution :) TY
